# Generated by Django 5.0.3 on 2026-08-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cancionero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancion',
            old_name='cancion',
            new_name='contenido',
        ),
    ]
